{% set name = "mopac" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmopac/mopac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b4c3959c36706ae06601819c5e057a261f2265d196986dd0c38ab63990dd17cd
  patches:
    - debug.patch  # [win]

build:
  number: 1

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - cmake
    - ninja
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_BIN%\\mopac.dll exit 1  # [win]
    - test -f $PREFIX/bin/{{ name }}-makpol  # [unix]
    - test -f $PREFIX/bin/{{ name }}-param  # [unix]
    - exit 1 # [win]
    - {{ name }} --version

about:
  home: http://openmopac.net
  dev_url: https://github.com/openmopac/mopac
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: The modern open-source version of the Molecular Orbital PACkage (MOPAC)

extra:
  recipe-maintainers:
    - awvwgk
    - godotalgorithm
