{% set name = "mopac" %}
{% set version = "23.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openmopac/mopac/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4e2381144f417352def26afee18c3e85dfafa37904ed643abe4dea6c995624b7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - cmake
    - ninja
    - python
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_BIN%\\libmopac.dll exit 1  # [win]
    - test -f $PREFIX/bin/{{ name }}-makpol  # [unix]
    - test -f $PREFIX/bin/{{ name }}-param  # [unix]
    - {{ name }} --version

about:
  home: http://openmopac.net
  dev_url: https://github.com/openmopac/mopac
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.lesser
  summary: The modern open-source version of the Molecular Orbital PACkage (MOPAC)

extra:
  recipe-maintainers:
    - awvwgk
    - godotalgorithm
